#!/usr/bin/env bash
# nginx & 301

sudo apt update
sudo apt -y install nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
new_str="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.github.com\/amasin76 permanent;"
sudo sed -i "s/server_name _;/$new_str/" /etc/nginx/sites-enabled/default

sudo nginx -t
sudo service nginx restart
