#!/usr/bin/env bash
# custom http response header

file=/etc/nginx/sites-available/default
phrase="/server_name _/a add_header X-Served-By $HOSTNAME;"
sudo sed -i "$phrase" $file

sudo nginx -t
sudo service nginx restart
