#!/usr/bin/env bash
# script that resetore nginx to default port
available=/etc/nginx/sites-available/default
enabled=/etc/nginx/sites-enabled/default
sudo ln -sf $available $enabled
sudo service ngnix restart
